### ISSUE TITLE
最新版在linux要安装gjs, cjs, nodejs?

### ISSUE THREAD

**Issue by andysendo** [SeaHOH/ykdl#383]
请问最新版在linux环境安装 gjs, cjs, nodejs 其中之一，有什么好处？是通过模拟浏览器更好的解析？

另：youku解析201客户端错误快半年了，安装js解释器能解决？youget可是可以但有的长视频只能解释2~3部分。

**Comment by coslyk** [comment]
斗鱼直播的解析需要运行JS代码。

**Comment by andysendo** [comment]
收到。
是不是可以考虑优酷解析也引入nodejs规避201错误和不能完整解析长视频

**Comment by coslyk** [comment]
> 收到。
> 是不是可以考虑优酷解析也引入nodejs规避201错误和不能完整解析长视频

优酷的JS需要调用浏览器的DOM，单纯的JS解释器跑不了的
NodeJS可以用[jsdom](https://www.npmjs.com/package/node-jsdom)模拟出DOM，但这样就要求用户自己安装Node环境，再用npm安装jsdom，有兴趣的可以自己试试，但这显然不是经济的做法 -_-

**Comment by airdge** [comment]
现在优酷对于ACS算法(0502/0519)限制比较大,并不是单纯算js_ckey就能解析到,解析几次就给你报错
之前js_ckey可以解析0512/0515全长独播视频,现在通通不行,
而且现在ups(0512)也只能解析一下非独播视频,碰上独播/电影还是解析不到的
所以我是不建议你们往这方面消耗时间,没啥必要
还不如命令行添加cookies参数选项,用ups(0590)去解析来的快
另外,也可以去找下旧apk接口,现在ctype=30的也都还在用

**Comment by coslyk** [comment]
@airdge ACS接口也是要带网页生成的cookies访问吧？感觉无论如何都要上cookies了:joy:
0590带登录过的cookies能解析全长嘛？

**Comment by airdge** [comment]
> @airdge ACS接口也是要带网页生成的cookies访问吧？感觉无论如何都要上cookies了😂
> 0590带登录过的cookies能解析全长嘛？


![default](https://user-images.githubusercontent.com/7813960/53926763-ac96b580-40bf-11e9-833d-dcb981fd128e.png)

应该是0512,没注意
```
from: http://player.youku.com/embed/XNDA0MDE0NjQ3Mg==?client_id=7c068d0cb01cb88c&password=&autoplay=false#127.0.0.1

referer: http://player.youku.com/embed/vid

ckey: DIl58SLFxFNndSV1GFNnMQVYkx1PP5tKe1siZu/86PR1u/Wh1Ptd+WOZsHHWxysSfAOhNJpdVWsdVJNsfJ8Sxd8WKVvNfAS8aS8fAOzYARzPyPc3JvtnPHjTdKfESTdnuTW6ZPvk2pNDh4uFzotgdMEFkzQ5wZVXl2Pf1/Y6hLK0OnCNxBj3+nb0v72gZ6b0td+WOZsHHWxysSo/0y9D2K42SaB8Y/+aD2K42SaB8Y/+ahU+WOZsHcrxysooUeND
```

**Comment by mengmo** [comment]
> > 收到。
> > 是不是可以考虑优酷解析也引入nodejs规避201错误和不能完整解析长视频
> 
> 优酷的JS需要调用浏览器的DOM，单纯的JS解释器跑不了的
> NodeJS可以用[jsdom](https://www.npmjs.com/package/node-jsdom)模拟出DOM，但这样就要求用户自己安装Node环境，再用npm安装jsdom，有兴趣的可以自己试试，但这显然不是经济的做法 -_-

不知道以下这些是否能有所帮助？
>
> https://pypi.org/project/beautifulsoup4/
>
> https://github.com/Knio/dominate/
>
> https://github.com/kata198/AdvancedHTMLParser
>
> https://github.com/html5lib/html5lib-python
>
> https://github.com/MechanicalSoup/MechanicalSoup
>
> https://github.com/python-mechanize/mechanize

**Comment by coslyk** [comment]
> > > 收到。
> > > 是不是可以考虑优酷解析也引入nodejs规避201错误和不能完整解析长视频
> > 
> > 
> > 优酷的JS需要调用浏览器的DOM，单纯的JS解释器跑不了的
> > NodeJS可以用[jsdom](https://www.npmjs.com/package/node-jsdom)模拟出DOM，但这样就要求用户自己安装Node环境，再用npm安装jsdom，有兴趣的可以自己试试，但这显然不是经济的做法 -_-
> 
> 不知道以下这些是否能有所帮助？
> 
> > https://pypi.org/project/beautifulsoup4/
> > https://github.com/Knio/dominate/
> > https://github.com/kata198/AdvancedHTMLParser
> > https://github.com/html5lib/html5lib-python
> > https://github.com/MechanicalSoup/MechanicalSoup
> > https://github.com/python-mechanize/mechanize

你发的这些是DOM的Python实现吧
获取ckey需要用JS模拟出DOM，才能跑优酷的ckey js

**Comment by mengmo** [comment]
有人看过这个吗？
https://github.com/nanipy/js.py
