### ISSUE TITLE
问一下为啥不用斗鱼手机端的api获取直播流呢？

### ISSUE THREAD

**Issue by daofeng2015** [SeaHOH/ykdl#420]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```
斗鱼网页端直播流加密已经做的非常复杂了....不知道有没有大神知道呢
如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by guest6379** [comment]
斗鱼也有PC客户端，有能力的大神也可以下载研究，PC客户端的API又是什么呢？

**Comment by jindaxia** [comment]
有空了 分析一下

**Comment by justasmalinauskas** [comment]
Can someone give me site url, to look at? As translate tools doesnt help me with this one :(

**Comment by xiatiantiantian** [comment]
> Can someone give me site url, to look at? As translate tools doesnt help me find that site :(

https://d.douyucdn.cn/wsd-pkg-div/2019/07/08/4b3ff3394ec0c068c49d9864446f4921_market_5.9.4_20190708221633.apk

**Comment by SeaHOH** [comment]
没必要 close 呀，说不定哪天哪位就解决掉这个。

@daofeng2015 请问你是已经确定这个没法解决吗？

**Comment by daofeng2015** [comment]
> 没必要 close 呀，说不定哪天哪位就解决掉这个。
> 
> @daofeng2015 请问你是已经确定这个没法解决吗？

 有个参数加密方法实在是找不到.....安卓反编译不是很熟悉..
