### ISSUE TITLE
ykdl有中断功能吗

### ISSUE THREAD

**Issue by chauncy42** [SeaHOH/ykdl#503]
按ctrl+c没反应

**Comment by orzogc** [comment]
有，按q键，下载时有提示的

**Comment by CJN1986** [comment]
@orzogc 请问这种情况下如何中止ykdl录制

A在12点前直播，12点之后是录播

写了个shell脚本(12点前运行ykdl录制A的内容，12点后强制结束ykdl录制)，在crontab里执行脚本。
因为是脚本，所以中止ykdl和ffmpeg的命令是
```bash
kill -9 "ykdl的pid" >/dev/null 2>&1 &
kill -9 "ffmpeg的pid" >/dev/null 2>&1 &
```
但这样的话录制的视频会出错，提示“moov atom not found”

不知道是不是我的操作方法不对？

**Comment by SeaHOH** [comment]
> 按ctrl+c没反应

内置下载功能运行时，这个是有用的。

> 有，按q键，下载时有提示的

这个是 FFmpeg 运行时可用。

**Comment by SeaHOH** [comment]
> 现在多任务下载也可以使用

Python 3.9 下好像失效了，还未仔细确认。
