### ISSUE TITLE
可以同步PyPI吗

### ISSUE THREAD

**Issue by ForgQi** [SeaHOH/ykdl#547]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]
如果开发的包需上传PyPI不能引用非PyPI域名下的依赖，所以没法用GitHub链接这种方式

**Comment by SeaHOH** [comment]
Owner 已经不再维护 ykdl 了，主要权限仍然在他手上。以前说过想转给我，但是考虑到水平有限，多是为了自己方便提交 commit，我就没有接受。当然，如果有人提需求且比较容易的，我也会添加。

如果还有比较多的用户，且觉得没有 PyPI 更新不方便，我可以联系 zhangn1985 让他全部转给我。但是，估计现在已经没有太多人还在用 ykdl 吧。

**Comment by ForgQi** [comment]
这是一个挺好的项目，应该还有挺多人用的，现在有GitHub Action上传PyPI应该成本不太高，希望大佬可以考虑一下

**Comment by SeaHOH** [comment]
你是怎么判断还有很多人在使用呢？我看到最近的统计是，两周内 400+ 的 repo 访问 (unique) 和 100+ 的 clone (unique)，以及 200+ 的 PyPI 月下载。各个站点也没怎么更新维护，具体情况可以查看近一年的 commits。

这些数据对于一个视频下载工具来讲实在是太少，而且整体一直在缓慢下降。关键还是缺少活跃的维护者，否则用户数量是上不来的。

**Comment by AronWater** [comment]
@SeaHOH 如果确实owner不再维护了    可以开多个repo （fork 的话我感觉也行  但始终别人比较难搜到)   

我个人感觉超过1k star的项目 都是很有影响力了

但基于pip install 可以直接  指定github 哪个commit  来install
所以pypl也未必是一个非常关键重要的任务

现在或许是让pull request等等可以更有流程的审批等等。

**Comment by ForgQi** [comment]
> @SeaHOH 如果确实owner不再维护了 可以开多个repo （fork 的话我感觉也行 但始终别人比较难搜到)
> 
> 我个人感觉超过1k star的项目 都是很有影响力了
> 
> 但基于pip install 可以直接 指定github 哪个commit 来install
> 所以pypl也未必是一个非常关键重要的任务
> 
> 现在或许是让pull request等等可以更有流程的审批等等。

如果开发的包需上传PyPI不能引用非PyPI域名下的依赖，这种情况下就没法用GitHub链接这种方式

**Comment by SeaHOH** [comment]
@ForgQi 我可以把权限要过来，但是缺少维护你以后也要换其它，建议你仔细考虑清楚。

**Comment by AronWater** [comment]
@ForgQi  所有任何用了ykdl的repo 都只能让用户自己把repo clone 下来 然后 pip install？

**Comment by SeaHOH** [comment]
@zhangn1985 你似乎过滤掉了我的邮件，因为没有找到其它联系方式我这里重复一下内容。

先是抱歉，ForgQi 没回复我最后的建议，兼之最近不怎么查看邮件，没想到当天你就发出所有权转移询问，以至错过。
我依旧跟之前一样，本身并不需要拥有 ykdl 的所有权。能否请你发个 issue 或 discussion 说明征求一个接任者，如果一段时间后仍然没有合适人选，那么我可以接手。

这里拜个早年。祝新年快乐，牛气冲天!

**Comment by StrollStars** [comment]
@SeaHOH 最开始安装的时候发现版本还是2018年的时候就吓了一跳，好在给的中文Wiki指引够详尽（谢谢 @zhangn1985 ），用了master.zip给升级上去了。
我在想用的人少会不会是更深层的原因——因缺少维护而可下载站点越来越少？因为需求一直都在，当初我为了下载一个西瓜视频花了好几个小时找工具。
其实相比同步PyPI，我觉得找到继任者更为重要，因为网站更新很频繁。而同类的几个工具，除了youtube-dl刚刚更新过，剩下的都停留在去年，其中[annie](https://github.com/iawia002/annie/releases)都怀疑是不是停更了。或许此类工具要像SS之类的形成项目才有未来，毕竟网站太多了。

**Comment by SeaHOH** [comment]
@StrollStars 是的，归根结底就是少维护。招募帖已经发布，希望能有行家接手，再不济多一两个维护者也是好的。话虽如此，但如果最后砸我手里的话，基本也只是维持现状而已，我个人并没有太大的需求，水平也有限。

**Comment by StrollStars** [comment]
@SeaHOH 是不是大家都基本在线观看，看完就算？即使如此还存在一点儿问题的。
另外可否考虑下联合另外两家成立个项目？毕竟我觉得这个靠单人是无法持久的。

**Comment by SeaHOH** [comment]
> 另外可否考虑下联合另外两家成立个项目？毕竟我觉得这个靠单人是无法持久的。

你这个发言过于随心所欲，实在不好与你细说，仅此一句：开源项目死掉再正常不过，贡献者大多是出于自身兴趣或需求，自愿参与，拿工资的另说。

**Comment by StrollStars** [comment]
@SeaHOH 我承认你说的情况，我只是想到了个人开发者的各种限制以及翻墙项目的持久，希望能有人接手吧。
PS：ykdl完成度挺高的，包括中文Wiki。
