### ISSUE TITLE
希望添加黑白直播

### ISSUE THREAD

**Issue by TaoziDB** [SeaHOH/ykdl#552]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> https://www.heibaizhibo.com/anchorLive
谢谢

**Comment by airdge** [comment]
看了下 是sojson的加密
这种使用量太少,花费开发者两三天时间去破解js,编写脚本不太实际

**Comment by TaoziDB** [comment]
请问现在还能用吗？

> 看了下 是sojson的加密
> 这种使用量太少,花费开发者两三天时间去破解js,编写脚本不太实际
> 
> ...
> 好像没做限制,只做了简单的加密
> 
> ```
> import requests,execjs,json
> jsUrl='https://pichb2.huoxinglaike.com/nuxt/static/m.js'
> js='var window={};'
> js+= requests.get(jsUrl).text.replace('==  typeof exports','!=  typeof exports')
> 
> vid='1292'
> url=f'https://sig.heibaizhibo.com/signal-front/live/matchLiveInfo?gtvId={vid}&source=2&liveType=3&defi=hd'
> 
> html=requests.get(url).text
> data=json.loads(html)
>  
> liveUrl=data["data"][0]["liveUrl"]
>  
> ctx = execjs.compile(js)
> flv = ctx.call("vp", liveUrl)
> print(flv)
> 
> 
> 
> https://livec.ali.huoxinglaike.com/live/zulanlunjian_hd.flv?auth_key=xxxx
> ```

**Comment by airdge** [comment]
> 请问现在还能用吗？
> 
> > 看了下 是sojson的加密
> > 这种使用量太少,花费开发者两三天时间去破解js,编写脚本不太实际
> > ...
> > 好像没做限制,只做了简单的加密
> > ```
> > import requests,execjs,json
> > jsUrl='https://pichb2.huoxinglaike.com/nuxt/static/m.js'
> > js='var window={};'
> > js+= requests.get(jsUrl).text.replace('==  typeof exports','!=  typeof exports')
> > 
> > vid='1292'
> > url=f'https://sig.heibaizhibo.com/signal-front/live/matchLiveInfo?gtvId={vid}&source=2&liveType=3&defi=hd'
> > 
> > html=requests.get(url).text
> > data=json.loads(html)
> >  
> > liveUrl=data["data"][0]["liveUrl"]
> >  
> > ctx = execjs.compile(js)
> > flv = ctx.call("vp", liveUrl)
> > print(flv)
> > 
> > 
> > 
> > https://livec.ali.huoxinglaike.com/live/zulanlunjian_hd.flv?auth_key=xxxx
> > ```

可以

**Comment by SeaHOH** [comment]
感谢 @airdge ！之前没看到你修改了回复。
