### ISSUE TITLE
请问怎样把代码打包成exe可执行文件呀，从哪个文件下手啊，跪求大佬解答，新手学习这个，拜托拜托( •︠ˍ•︡ )

### ISSUE THREAD

**Issue by Hello-everybody** [SeaHOH/ykdl#567]
请问怎样把代码打包成exe可执行文件呀，从哪个文件下手啊，跪求大佬解答，新手学习这个，拜托拜托( •︠ˍ•︡ )

**Comment by Hello-everybody** [comment]
@SeaHOH  求大佬解答，指点，忠实粉丝，第一次提问●‿●

**Comment by SeaHOH** [comment]
具体方法请从上方 wiki 链接查看

**Comment by Hello-everybody** [comment]
> 具体方法请从上方 wiki 链接查看

请问链接在哪呢，(*• . •*)?

**Comment by Hello-everybody** [comment]
> 具体方法请从上方 wiki 链接查看

看到啦，谢谢，爱你😘
