### ISSUE TITLE
About pypi artifact

### ISSUE THREAD

**Issue by chenrui333** [SeaHOH/ykdl#572]
It looks like for the most recent releases, the pypi artifact is missing, just want to raise an issue in here to confirm if that is intentional, thanks!!

The rationale behind is if we can have the tgz file published into pypi index, we can make the dependencies more clear in the homebrew side.

--

- https://github.com/Homebrew/homebrew-core/pull/81481

**Comment by SeaHOH** [comment]
Now, tgz pkg has published, enjoy it!

**Comment by chenrui333** [comment]
Thanks @SeaHOH!
