### ISSUE TITLE
添加ffmpeg的参数"-movflags +faststart"

### ISSUE THREAD

**Issue by CJN1986** [SeaHOH/ykdl#576]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

添加-movflags +faststart后可以方便网络观看录制的视频。
https://github.com/SeaHOH/ykdl/blob/2242de9e0017b383c846661a8c9baf2dd0e8209f/ykdl/util/wrap.py#L201
在这一行下面添加参数的，不知道是否正确？或者是否有其它问题？
`'-movflags', '+faststart',`

**Comment by SeaHOH** [comment]
只是`copy`流而不是**recode**，不太清楚是否有用。

**Comment by CJN1986** [comment]
没效果是不是指视频上传到平台后再被压缩？
有一种情况是直链视频，比如：http://ip/a.mp4。

**Comment by wordlesswind** [comment]
> 没效果是不是指视频上传到平台后再被压缩？
> 有一种情况是直链视频，比如：[http://ip/a.mp4。](http://ip/a.mp4%E3%80%82)

再压制是另一回事，这里说的是 ykdl 调用 ffmpeg 只是将视频流和音频流转录到一个媒体文件中，相当于 下载/复制，不涉及修改。

你如果要使用 `-movflags +faststart`，那就得 下载/复制 完以后，才执行：
```
ffmpeg -hide_banner -i input.flv -c copy -movflags +faststart output.mp4
```
而且这两个参数是对于 MP4 容器来说的，FLV 没有这种东西。

**Comment by CJN1986** [comment]
明白了
