### ISSUE TITLE
爱奇艺下载出错

### ISSUE THREAD

**Issue by StrollStars** [SeaHOH/ykdl#577]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
ERROR:downloader:download failed at parts: 45, 46, 47, 48, 49, 50, 51, 52, 53, 5
4, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 7
4, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 320, 321, 322
, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338
, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354
, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369
The estimated ETA is N/A, do you want to continue downloading? [Y]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [最后的赢家第1回：李易峰智斗泥鳅 秦霄贤被困鸡窝沦为喂食器](https://www.iqiyi.com/v_16zxzex10v0.html)视频无法下载，但是有的爱奇艺视频是能够下载的，麻烦看下是哪里的问题。

**Comment by SeaHOH** [comment]
几百个分段中出现部分下载失败是正常现象，按提示操作继续下载即可。
下载失败只会在特定的条件下自动重试，其它情况需用户确认，不然可能在某些情况下卡死循环。

**Comment by StrollStars** [comment]
但是按Y继续失败，连续3次都是，我就直接关闭了。
然后奇怪的来了，我换用you-get和youtube-dl，都是一样的报错，当然我没去核对每一个下载部分是否一致。
是不是说明三者的下载机制很像甚至是一样？所以是不是遇到了共性的问题？
本来也想去you-get反馈的，但是它的Pull requests方式我不会用。

**Comment by SeaHOH** [comment]
我这里是正常的，怀疑是你的网络问题，如 DNS 没有返回适合的 CDN 服务器，或不小心使用了代理-。

**Comment by StrollStars** [comment]
你下载到的是947.8MB的，还是上GB的？

**Comment by SeaHOH** [comment]
4K，下载量接近 1G，合并后 947.8M。
1080P，下载量接近 1G，合并后 946.7M。

**Comment by StrollStars** [comment]
我换了太电脑，下载成功了，得到的体积跟你一样大，但是你不觉得奇怪吗？4K和1080P体积相差如此之小。
对比下我下载成功的它的前作[最后的赢家序幕：李易峰赵又廷查案掉陷阱 关晓彤成看热闹专业户](https://www.iqiyi.com/v_23x5j07otbc.html)，37分钟的体积接近1GB，而这个接近1小时的体积也只有1GB不到，所以是有问题的。

**Comment by SeaHOH** [comment]
分辨率和体积无关，那确实是 4K。
