### ISSUE TITLE
代码的规范和清理

### ISSUE THREAD

**Issue by SeaHOH** [SeaHOH/ykdl#579]
- [x] 完全移除不再使用的 **Python 3.4** 及以下版本遗留代码。
- [x] 将 extractors 经常使用的 class 和 function 等集中到公共 module 中，方便一次性导入。
- [x] 在上述公共 module 中添加一些可以简化代码量的 wrap (包装)，方便 extractors 维护者调用和阅读。
- [x] 调整部分 module 名称，移动代码到适合名称/功能的 module 中。
- [x] 上述过程中，顺便将代码风格调整至统一，调整添加必要的注释说明。
- [x] 分离与 **ykdl** 没有密切关系、又具备自成一体完整功能的 module，将其作为单独的 package 维护发布。

这些调整一方面是出于我自身使用需求；另一方面，看本项目访问统计不太热闹的样子，希望调整后更易于使用和维护，能吸引到更多的用户和参与简单维护的贡献者。

**Comment by coslyk** [comment]
@SeaHOH 你管理吧，我准备毕业工作了，之后应该不太有时间了。你以后也不用问我的：）

**Comment by SeaHOH** [comment]
了解。祝事业有成！

**Comment by SeaHOH** [comment]
总算将计划完成了一半，剩下的部分工作已经在前面的过程中逐步修改，但是期间又萌发了些其它想法，整体完成时间还要拉长，所以决定把已完成部分检查后就先合并。

这里想请有兴趣的小伙伴帮忙试用，看看是否有什么 bug，我估计是有的，但要我自己查的话实在是太费时间了。

大概是这么个安装命令：
``` console
pip3 install https://github.com/SeaHOH/ykdl/archive/refs/heads/code-clear.zip --force-reinstall --no-deps
pip3 install https://github.com/SeaHOH/ykdl/archive/refs/heads/code-clear.zip --upgrade
```

**Comment by SeaHOH** [comment]
为修复 bug，#580 已合并，后续进度另行 PR。

**Comment by SeaHOH** [comment]
添加了一些新特性：
- 支持相同格式代码的多个流
- 指定格式时支持回退到较低质量而不是最高质量
- 支持加密 M3U

**Comment by SeaHOH** [comment]
基本上完成了，发个 beta 版本。
