### ISSUE TITLE
下载失败提示语句请教

### ISSUE THREAD

**Issue by StrollStars** [SeaHOH/ykdl#581]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/SeaHOH/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/SeaHOH/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`或其依赖，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> The estimated ETA is N/A, do you want to continue downloading? [Y]

请问这种错误是不是无法用`--fail-retry-eta SECONDS`参数解决，只能手动Y？
PS：ETA是什么意思？预计完成时间？
> ERROR:downloader:download failed at parts: 354
CRITICAL:YKDL:xxx> donwload failed

这是加了`--no-fail-confirm`参数后错误直接停止了，是不是为了避免死循环，所以没有一直尝试下载，也就是说要去掉该参数手动确认继续下载？

**Comment by SeaHOH** [comment]
ETA 是 Estimated Time of Arrival 的缩写，消息中有重复第一个缩写作为提示。

要求用户确认确实是为了避免死循环，使用 `--no-fail-confirm` 可避免阻塞自动任务。

`N/A` 的情况无法获取文件大小，所以不会重试，反之会先重试两次才要求确认。

**Comment by StrollStars** [comment]
用了`--no-fail-confirm`之后，是不是跳过错误继续往下执行了？
可否增加支持最多重试次数以应对`N/A`的情况？

**Comment by SeaHOH** [comment]
> 用了`--no-fail-confirm`之后，是不是跳过错误继续往下执行了？

对，直接忽略错误，所有任务都完成后，出错的那些就是未完全下载成功的状态。

> 可否增加支持最多重试次数以应对`N/A`的情况？

可以是可以，但这里有个情况是这样：`N/A` 意味着无法支持续传，如果每次都是下载到后半才出错，小文件还好，那些非常大的文件会造成无法预估的浪费。所以最后决定不自动重试这类错误。

**Comment by StrollStars** [comment]
> 可以是可以，但这里有个情况是这样：N/A 意味着无法支持续传，如果每次都是下载到后半才出错，小文件还好，那些非常大的文件会造成无法预估的浪费。所以最后决定不自动重试这类错误。

那是否方便加个参数，后跟自动重试次数，默认不启用，这样就看下载者的选择了。

**Comment by SeaHOH** [comment]
其实不光是浪不浪费的问题，绝大部分情况下这么做都是毫无收益的，而且有时候可能是负收益 (因覆盖下载完成度可以比之前更少，最低为 0)，甚至还可能造成其它恶劣的后果。

所谓用户自担责任这种声明其实是有限制对象的，也就是提供者要先选择合适的渠道 (任意) 及对象 (先天限于产品本身属性，后限于渠道)，如果无任何限制 (一般用户不会去完全理解只是普通地使用提供的功能) 这个责任是逃不掉的。虽然网上匿名，但人没法欺骗自己。

所以，恕我不能提供此功能，万望谅解。

**Comment by StrollStars** [comment]
我明白了，感谢你的耐心解答。
