### ISSUE TITLE
抖音直播失效

### ISSUE THREAD

**Issue by a67878813** [SeaHOH/ykdl#588]
douyin/live.py
21: html = get_content()
内容不全， 也需要js处理
22data match不到。

**Comment by SeaHOH** [comment]
节后再搞。

**Comment by SeaHOH** [comment]
有点麻烦，需要浏览器环境，否则没法直接加载 js 获取设置 cookie 需要的 sign 函数。

**Comment by a67878813** [comment]
@SeaHOH 轻量的浏览器环境有哪些选择？ js反混淆可行吗？

**Comment by SeaHOH** [comment]
> 轻量的浏览器环境有哪些选择？

PhantomJS? 可惜开发早已停滞，适用范围可能受限。
NodeJS + jsdom，感觉不算轻。

其实我也不想引入太多重的依赖，纠结。
有点想基于 quickjs 做一个 NodeJS 兼容的工具，类似 dukpy 那样，但又觉得这事不该我来主持。

> js反混淆可行吗？

应该可以，但我没有经验，混得稍微过分点的都搞不来。
倒是可以反复注入调试代码来硬嗑，找出所有 break call，但是我不喜欢这样，之后估计会尝试一下自动化这个过程。

---

其实也许可以另辟蹊径，直接调用 Web API 之类。不过不清楚反爬范围，反正桌面版没戏，数据都直接内嵌网页。分类页面倒是没有反爬，而且内嵌有给出的房间的数据，但是不能指定房间我们也用不上啊。

**Comment by SeaHOH** [comment]
搞定了。之前一直以为要按照网页代码初始化，结果才发现不用 `byted_acrawler.init` 直接 `byted_acrawler.sign` 也行。

**Comment by SeaHOH** [comment]
西瓜、火山之类的好像也可以这样搞。
