### ISSUE TITLE
处理跳转链接

### ISSUE THREAD

**Issue by wordlesswind** [SeaHOH/ykdl#590]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/SeaHOH/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/SeaHOH/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`或其依赖，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl --debug -i https://t.cn/
DEBUG:html:Add <urllib.request.ProxyHandler object at 0x00000176795FC8B0> to default handlers
DEBUG:common:video_host> t.cn
DEBUG:common:short_name> t
DEBUG:common:> Try HTTP Redirection!
DEBUG:common:> NO HTTP Redirection
DEBUG:common:> Go Generalembed
DEBUG:html:get_content> URL: https://t.cn/
DEBUG:html:get_content> Charset: gb2312
ERROR:YKDL:Playlist is not supported for GeneralEmbed (通用嵌入视频)with url: https://t.cn/
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 只是想偷个懒，比如 `t.cn`、`dwz.cn`、`url.cn` 和 `b23.tv` 等跳转链接，现在 ykdl 无法处理。

**Comment by SeaHOH** [comment]
请更新到 Beta 测试版本，可以满足此需求。近期将会发布正式版本，预计还有一个预览版本。

例外：微博的短链接会一直跳转，直到登录链接，等会儿会处理一下这个情况。
