### ISSUE TITLE
skip done files

### ISSUE THREAD

**Issue by kucingkembar** [SeaHOH/ykdl#595]
sorry it's me again, for my bad English, and I have zero experience with Chinese reading
I tried answer based on the template

Please make sure you have checked the following before submitting!

    [yes, I can] You can indeed watch videos in your browser or mobile, but you can't download them using ykdl.
    [yes] Your ykdl is up to date.
    [yes] You have read and followed the instructions in https://github.com/SeaHOH/ykdl/wiki.
    [I can't read Chinese, so I have some difficulty looking if this issue exists or not] Your issue is not reported in https://github.com/SeaHOH/ykdl/issues, otherwise please report it under the original issue.
    [yes] This question is really about ykdl or its dependencies, not about other projects.
If you have other postscripts, such as the question only occurs on a certain video, or a general discussion or a suggestion for a new feature, please add it below:

[
is this software support command that equal to this:
`--download-archive Done.txt --no-post-overwrites`
(it from yt-dlp)
I looked at the documentation but there is nothing about this feature,
is this feature available in the current version?
is this feature available soon?

thank you for reading, the hard work, and have a nice day
]

**Comment by SeaHOH** [comment]
In YKDL, there has no equal commands as `--download-archive` or `--no-post-overwrites`.
But, we have always skiped done file if its filename and filesize are matched with the output when use internal download. Output with uncertain filesize will overwrite existing file, with certain filesize can resumes uncompleted downloading.
External download, now they are live m3u (there is a timestamp, in fact it never be overwrited), mpd.

You can use `-h` or `--help` to get all valid commands (document in English).

**Comment by kucingkembar** [comment]
thank you for the reply,
some software usually has a hidden or experimental feature, 
so I ask if this kind of feature exists,
thank you again, you can close this issue

**Comment by SeaHOH** [comment]
You are always welcome : )
