### ISSUE TITLE
Fail to play bilibili live video with mpv

### ISSUE THREAD

**Issue by fraic** [SeaHOH/ykdl#599]
Find a message in mpv log:
    
        HTTP Error 475

But download with ffmpeg is ok.

**Comment by SeaHOH** [comment]
First, show me a URL. And where you are, can you write in Chinese?

**Comment by fraic** [comment]
大部分直播间好像都不行
比如：

ykdl -p mpv https://live.bilibili.com/545068

mpv立即退出了

其他网站都正常，只有B站有问题

但是

ykdl https://live.bilibili.com/545068

这样下载是可以的

**Comment by SeaHOH** [comment]
无法复现。

你使用的 mpv 是什么版本的，系统环境变量 `http_proxy` 是否有设置？

**Comment by SeaHOH** [comment]
我这里也开始出现 flv 请求 475。

**Comment by SeaHOH** [comment]
添加 `referer` 后解决问题。
