### ISSUE TITLE
斗鱼直播无法下载 Playlist is not supported for GeneralEmbed (通用嵌入视频)with url

### ISSUE THREAD

**Issue by yoyosnart** [SeaHOH/ykdl#601]
在提交前，请确保您已经检查了以下内容!

- [x] 你的问题无关 VIP 内容。**YKDL** 不会主动支持 VIP 内容，相关问题一概不予受理。
- [x] 你确实可以在浏览器或移动端中正常播放，但不能使用 **YKDL** 下载。
- [ ] 你的 **YKDL** 为最新版。
- [x] 你已经阅读并按 https://github.com/SeaHOH/ykdl/wiki 中的指引进行了操作。
- [x] 你的问题没有在 https://github.com/SeaHOH/ykdl/issues 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于 **YKDL** 或其依赖，而不是其他项目。

请将错误输出粘贴在下面:

```
C:\Users\pig>ykdl https://www.douyu.com/1126960 --debug
DEBUG:html:Add <urllib.request.ProxyHandler object at 0x03B7AED0> to default handlers
DEBUG:common:video_host> www.douyu.com
DEBUG:common:short_name> douyu
DEBUG:common:> Try HTTP Redirection!
DEBUG:common:> new url https://www.douyu.com/topic/EDG_theme2?rid=1126960
DEBUG:common:video_host> www.douyu.com
DEBUG:common:short_name> douyu
DEBUG:common:> Try HTTP Redirection!
DEBUG:common:> NO HTTP Redirection
DEBUG:common:> Go Generalembed
DEBUG:html:get_content> URL: https://www.douyu.com/topic/EDG_theme2?rid=1126960
DEBUG:html:get_content> Charset: UTF-8
ERROR:YKDL:Playlist is not supported for GeneralEmbed (通用嵌入视频)with url: https://www.douyu.com/topic/EDG_theme2?rid=1126960
```

如果你有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by SeaHOH** [comment]
请通过正常方式安装，确保文件完整性。

**Comment by yoyosnart** [comment]
> 请通过正常方式安装，确保文件完整性。

更新后已解决 但变成ffmpeg报错
[flv @ 00000280c2b9e800] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
av_interleaved_write_frame(): Invalid data found when processing input
