### ISSUE TITLE
1.8.1版本ykdl/util/http.py报错，ImportError: cannot import name 'NoneType' from 'types' (/usr/lib/python3.8/types.py)

### ISSUE THREAD

**Issue by ForgQi** [SeaHOH/ykdl#604]
在提交前，请确保您已经检查了以下内容!

- [ ] 你的问题无关 VIP 内容。**YKDL** 不会主动支持 VIP 内容，相关问题一概不予受理。
- [ ] 你确实可以在浏览器或移动端中正常播放，但不能使用 **YKDL** 下载。
- [ ] 你的 **YKDL** 为最新发布版本，或开发版本。
- [ ] 你已经阅读并按 https://github.com/SeaHOH/ykdl/wiki 中的指引进行了操作。
- [ ] 你的问题没有在 https://github.com/SeaHOH/ykdl/issues 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于 **YKDL** 或其依赖，而不是其他项目。

请将错误输出粘贴在下面:

```
 from .util.http import get_head_response
  File "/usr/local/lib/python3.8/dist-packages/ykdl/util/http.py", line 10, in <module>
    from types import NoneType
ImportError: cannot import name 'NoneType' from 'types' (/usr/lib/python3.8/types.py)

```

如果你有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

**Comment by SeaHOH** [comment]
非常感谢！
单元测试这方面一直未恢复，所以有出现此种状况。但是我暂时没有精力来整理这方面的内容，估计要等到 2.0 整个代码构架流程整理的差不多了才会开始着手。
