### ISSUE TITLE
>但是目前最新的网页，貌似没有运行这个地方的代码，断点断不到这个位置。目前发现这个加密是跟url地址有关系

### ISSUE THREAD

**Issue by zc16607** [SeaHOH/ykdl#612]
> 
> 
> > > 看了下，貌似是对I帧进行了加密，加密的操作在[liveplayer_controls.js](https://js.player.cntv.cn/creator/liveplayer_controls.js)下面的一坨（应该是魔改版本的hls.js），[原本的逻辑](https://github.com/video-dev/hls.js/blob/v0.12.4/src/demux/tsdemuxer.js#L581)
> > > ![捕获](https://user-images.githubusercontent.com/12208550/72737039-bd69f000-3bd9-11ea-8a46-727e31d7949b.PNG)
> > > Module里的函数是[h5.worker](https://js.player.cntv.cn/creator/h5.worker?v=200113)提供的，貌似用了wasm，暂时没啥好办法
> > 
> > 
> > 应该是用JS解密吧……
> 
> h5.worker最开始的字符串就是base64过的wasm

[WABT: The WebAssembly Binary Toolkit](https://github.com/WebAssembly/wabt)
无论用哪个工具转换出来的东西都不少，看着头晕。

_Originally posted by @mengmo in https://github.com/SeaHOH/ykdl/issues/442#issuecomment-581257985_

**Comment by joaopa00** [comment]
Only the first page of pojie site is available without subscription. Is there any progress freely available?
