### ISSUE TITLE
腾讯视频解析出的profile不全

### ISSUE THREAD

**Issue by karma-sun** [SeaHOH/ykdl#613]
腾讯视频只能获取480p的profile,实际网页版有三种profile

请将错误输出粘贴在下面:

```
ykdl -i https://v.qq.com/x/cover/mzc0020017vjb8z/v00430bfzh1.html
site:                 腾讯视频 (QQ)
title:                仙墓_01
streams:
    - format:         HD
      container:      mp4
      video-profile:  标清;(480P)
      size:           102.574 MiB (107556485 Bytes)
    # download-with:  ykdl --format=HD [URL]
```

如果你有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

[在这里输入内容文本]

**Comment by karma-sun** [comment]
腾讯这个貌似和用户无关，因为刚测试网页版用上面示例的链接，即使不登录任何用户，也可以看到三种profile，并且正常看720p

**Comment by SeaHOH** [comment]
腾讯的情况是浏览器自动登录匿名用户，这个过程采用了有效的加密措施，不太方便通过纯脚本模拟。个别有效的采集工具貌似都是通过无头浏览器，或者干脆就是浏览器扩展插件之类。

**Comment by basheewang** [comment]
> 已经好几年了，我也没有什么好办法。这个月 B站也对新投稿采取了类似的策略，需要新 API 登录才能取得更高的画质，但是 ykdl 约定过不支持加载 cookies，所以也只能看渣画质。

正打算open这个ticket，原来是这个原因。B站以后只能网页看了……可惜。
