### ISSUE TITLE
 DEPRECATION: ykdl is being installed using the legacy 'setup.py install' method

### ISSUE THREAD

**Issue by wordlesswind** [SeaHOH/ykdl#614]
在提交前，请确保您已经检查了以下内容!

- [x] 你的问题无关 VIP 内容。**YKDL** 不会主动支持 VIP 内容，相关问题一概不予受理。
- [x] 你确实可以在浏览器或移动端中正常播放，但不能使用 **YKDL** 下载。
- [x] 你的 **YKDL** 为最新发布版本，或开发版本。
- [x] 你已经阅读并按 https://github.com/SeaHOH/ykdl/wiki 中的指引进行了操作。
- [x] 你的问题没有在 https://github.com/SeaHOH/ykdl/issues 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于 **YKDL** 或其依赖，而不是其他项目。

请将错误输出粘贴在下面:

```
DEPRECATION: ykdl is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

如果你有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

直接安装 `wheel` 然后在进行 `setup.py install` 的方式似乎会被弃用，之后必须启用 `--use-pep517` 标识。

**Comment by SeaHOH** [comment]
已确认，pip 从源安装会显示此警告。添加 `pyproject.toml` 与启用 `--use-pep517` 是等价的，前者是强制采用 pep517。

> 直接安装 `wheel` 然后在进行 `setup.py install` 的方式似乎会被弃用

如果当前环境安装有 wheel 也不会触发此警告，这是默认的安装格式。直接 `setup.py install` 始终是可用的，弃用是指 pip 之后不再支持回落到调用此旧安装方法。
