### ISSUE TITLE
Bilibili bangumi解析使用了过时的API

### ISSUE THREAD

**Issue by karma-sun** [SeaHOH/ykdl#619]
Bilibili解析使用的https://bangumi.bilibili.com/player/web_api/v2/playurl貌似过时了？不能获得完整的profile list
事实上视频信息就在网页源代码里，有类似window.__playinfo__=XXX 的JS

**Comment by SeaHOH** [comment]
感谢提醒！这是一个已知问题。

保留此 API 的原因：
- 它仍然获取多个 profile 结果，前提是目标视频发表于 11 月之前。
- 相比当前的 `360p`，网页中提供的 profile 也只是多了 `480p`。
- 使用新 API 可以获取更多的 profile，但需要登录，而 ykdl 并不对外提供任何 cookies 功能 (设计如此，以后也不会提供)。

如果有了新的想法，欢迎继续交流。
