### ISSUE TITLE
download video with 480p and over 

### ISSUE THREAD

**Issue by kucingkembar** [SeaHOH/ykdl#620]
sorry for my bad English, I use google translate so I tried to answer based on the template

Please make sure you have checked the following before submitting!
    [checked] Your question has nothing to do with VIP content. YKDL will not actively support VIP content, and related questions will not be accepted.
    [checked] You can indeed play normally in browsers or mobile devices, but you cannot use YKDL to download.
    [checked] Your YKDL is the latest release version or development version.
    [checked] You have read and followed the instructions in https://github.com/SeaHOH/ykdl/wiki.
    [i cannot read Chinese, and the Google Translate version may be missing the translation] Your issue is not reported in https://github.com/SeaHOH/ykdl/issues, otherwise please report it under the original issue.
    [checked] This question is really about YKDL or its dependencies, not other projects.

Please paste the error output below:
```
[]
```
If you have other postscripts, such as the problem only occurs with a certain video, or a general discussion or suggesting a new feature, please add it below:
```
[]
```

sorry again for my bad English,
I like to download videos from bilibili.com, 
but now, non-logged users are only allowed to watch 360p, 
above it (480p, 720p, 1080p) only allowed for logged user,
[note: 1080p 60fps and above count as VIP User]
can this software download them?

anyway, I do not have a "Registered Account", 
only pre-log using my phone number, 
so I can watch 1080p (not 60Fps mode)
how to use this "account" to download 720p videos?

thank you for reading,
have a nice day,
keep healthy

**Comment by SeaHOH** [comment]
For bilibili.com, YKDL can only download 360P videos which uploaded after Nov 2022, old videos are unacted.
The policy has been changed since the time point mentioned above, user must be login for watching high quality now, but login or load external cookies is out of YKDL's roadmap, so I will do nothing.

BUT, at now time, there are many other tools support login and download from bilibili.com, you can just search inside github.com.

**Comment by kucingkembar** [comment]
thank you, you can close it
