### ISSUE TITLE
huya 直播不能下载了请求更新

### ISSUE THREAD

**Issue by fxsee1** [SeaHOH/ykdl#626]
huya 直播不能下载了请求更新，非直播视频也下载不了

**Comment by SeaHOH** [comment]
除了「一起看」个别房间，其余未发现无法正常观看的情况。你这是全部都不能下载吗？安装 FFmpeg 没？

**Comment by fxsee1** [comment]
我一直在用有几年了，虎牙直播下不了，前天刚改的，斗鱼可以。你可以参考一下biliup，他已经修改好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月30日(周日) 上午9:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SeaHOH/ykdl] huya 直播不能下载了请求更新 (Issue #626)




 
除了「一起看」个别房间，其余未发现无法正常观看的情况。你这是全部都不能下载吗？安装 FFmpeg 没？

**Comment by fxsee1** [comment]
我问题没说清楚，虎牙直播下载断流，只能下载几秒就断了，你可以参考biliup，他已修改好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月30日(周日) 上午9:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SeaHOH/ykdl] huya 直播不能下载了请求更新 (Issue #626)




 
除了「一起看」个别房间，其余未发现无法正常观看的情况。你这是全部都不能下载吗？安装 FFmpeg 没？

**Comment by SeaHOH** [comment]
@fxsee1 @lolvod
两位，你们反馈的无法下载是针对所有房间吗？biliup 使用的网址加密方法和 ykdl 是一致的。

就我这里测试的情况，只有个别房间无法下载，这点刚才也找到原因了。因为不是所有房间都需要重新加密网址，ykdl 这里有一个判断，当前判断条件有遗漏，补全条件或者全部都重新加密也行。

**Comment by fxsee1** [comment]
biliup 昨天刚更新 
[root@amd200 lol202210]# ykdl https://www.huya.com/bagea
site:                 Huya Live (虎牙直播)
title:                「霸哥 - 峡谷上分」
artist:               霸哥
streams:
    - format:         BD8M
      container:      flv
    # download-with:  ykdl --format=BD8M [URL]

Now downloading: 「霸哥 - 峡谷上分」_BD8M_2023-07-30T14:06:32.flv
WARNING:ykdl.util.external:
=================================
  stop downloading by press 'q'
=================================

Input #0, flv, from 'http://tx.flv.huya.com/src/1724691-1724691-7407491440705536-3572838-10057-A-0-1-imgplus.flv?wsSecret=6548200961c34a46dba5637d668644e4&wsTime=64c5fdfd&fm=RFdxOEJjSjNoNkRKdDZUWV8kMF8kMV8kMl8kMw%3D%3D&ctype=huya_live&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500,264_2000,264_4000,264_8000,':
  Metadata:
    codecname       : 0
    server          : TLSS/2.0.0(qcloud)
    server_version  : 2.0.0
  Duration: N/A, start: 18208.033000, bitrate: N/A
  Stream #0:0: Subtitle: text
  Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp
  Stream #0:2: Video: h264 (High), yuv420p(tv, smpte170m, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 1k tbn
Output #0, flv, to '「霸哥 - 峡谷上分」_BD8M_2023-07-30T14:06:32.flv':
  Metadata:
    codecname       : 0
    server          : TLSS/2.0.0(qcloud)
    server_version  : 2.0.0
    encoder         : Lavf60.7.100
  Stream #0:0: Video: h264 (High) ([7][0][0][0] / 0x0007), yuv420p(tv, smpte170m, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 60 tbr, 1k tbn
  Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp
Stream mapping:
  Stream #0:2 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[http @ 0x4a83540] Stream ends prematurely at 1309701, should be 18446744073709551615
    Last message repeated 1 times
[in#0/flv @ 0x4a827c0] Error during demuxing: Input/output error
[in#0/flv @ 0x4a827c0] Error retrieving a packet from demuxer: Input/output error
[out#0/flv @ 0x4bbe740] video:1000kB audio:258kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.690368%
frame=  661 fps=0.0 q=-1.0 Lsize=    1279kB time=00:00:11.00 bitrate= 952.7kbits/s speed=47.2x

**Comment by fxsee1** [comment]
[修复虎牙拉流403分段问题](https://github.com/biliup/biliup/commit/6ef1bd92522d924f2c4e7f6dd82bebe369c036cb)https://github.com/biliup/biliup/issues/558 [(](https://github.com/biliup/biliup/commit/6ef1bd92522d924f2c4e7f6dd82bebe369c036cb)https://github.com/biliup/biliup/pull/561[)](https://github.com/biliup/biliup/commit/6ef1bd92522d924f2c4e7f6dd82bebe369c036cb)
2 days ago

**Comment by SeaHOH** [comment]
> [root@amd200 lol202210]# ykdl https://www.huya.com/bagea

这个房间现在没有直播。

请看[这里的说明](url)，明确回复我的问题。

**Comment by SeaHOH** [comment]
> [root@amd200 lol202210]# ykdl https://www.huya.com/bagea

这个房间现在没有直播。

请看[这里的说明](https://github.com/SeaHOH/ykdl/issues/626#issuecomment-1657082168)，明确回复我的问题。

**Comment by fxsee1** [comment]
别的有直播的房间也一样 你试一下 ykdl https://www.huya.com/majiajia

**Comment by SeaHOH** [comment]
> 别的有直播的房间也一样 你试一下 ykdl https://www.huya.com/majiajia

对了，就是这样，哪个房间不能下载都反馈给我，好方便补全判断条件。

**Comment by fxsee1** [comment]
你可以参考一下 biliup的 huya.py ，我自己水平不行，要不然自己就帮你改了

**Comment by SeaHOH** [comment]
> 你可以参考一下 biliup的 huya.py ，我自己水平不行，要不然自己就帮你改了

我写的字你看得懂吧，我觉得我有把这个问题产生的原因描述清楚。

**Comment by fxsee1** [comment]
好吧，我自己改吧

**Comment by SeaHOH** [comment]
你想要自己改也行，不过你确定有明白我在说什么吗？

**Comment by fxsee1** [comment]
反正我这两天用ykdl 下载huya的下载不了，下载douyu与B站的没问题，2天前下载huya直播也没问题，还有我用YKDL至少5年了

**Comment by SeaHOH** [comment]
不是，这有什么好较劲的，哪里有问题反馈就是，然后肯定会需要具体信息来确定原因，所以会向你询问。
但总是不告诉我想了解的信息，只是说之前好的，现在坏了，别人修复了，这样对解决问题并没有更多的帮助。

**Comment by SeaHOH** [comment]
修改了判断条件，试试是否能正常下载。

**Comment by SeaHOH** [comment]
实践下来发现容易遗漏条件，所以移除判断，恢复成所有下载网址都会重新加密。

**Comment by fxsee1** [comment]
可以了下载虎牙，谢谢
