### ISSUE TITLE
虎牙直播 下载几秒就断流，前天刚改了，不能正常下载，biliup以修正，可以参考

### ISSUE THREAD

**Issue by lolvod** [SeaHOH/ykdl#627]
在提交前，请确保您已经检查了以下内容!

- [ ] 你的问题无关 VIP 内容。**YKDL** 不会主动支持 VIP 内容，相关问题一概不予受理。
- [ ] 你确实可以在浏览器或移动端中正常播放，但不能使用 **YKDL** 下载。
- [ ] 你的 **YKDL** 为最新发布版本，或开发版本。
- [ ] 你已经阅读并按 https://github.com/SeaHOH/ykdl/wiki 中的指引进行了操作。
- [ ] 你的问题没有在 https://github.com/SeaHOH/ykdl/issues 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于 **YKDL** 或其依赖，而不是其他项目。

请将错误输出粘贴在下面:

```
虎牙直播 下载几秒就断流，前天刚改了，不能正常下载，biliup以修正，可以参考

```

如果你有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

[在这里输入内容文本]

**Comment by SeaHOH** [comment]
Duplicate of #626
