### ISSUE TITLE
爱奇艺无法下载视频

### ISSUE THREAD

**Issue by RaGNaroK0301** [SeaHOH/ykdl#636]
在提交前，请确保您已经检查了以下内容!

- [√] 你的问题无关 VIP 内容。**YKDL** 不会主动支持 VIP 内容，相关问题一概不予受理。
- [√] 你确实可以在浏览器或移动端中正常播放，但不能使用 **YKDL** 下载。
- [√] 你的 **YKDL** 为最新发布版本，或开发版本。
- [√] 你已经阅读并按 https://github.com/SeaHOH/ykdl/wiki 中的指引进行了操作。
- [√] 你的问题没有在 https://github.com/SeaHOH/ykdl/issues 报告，否则请在原有 issue 下报告。
- [√] 本问题确实关于 **YKDL** 或其依赖，而不是其他项目。

请将错误输出粘贴在下面:
ykdl -i https://www.iqiyi.com/v_mt2g0kpnn4.html --debug

DEBUG:ykdl.util.http:get_response> URL: https://www.iqiyi.com/v_mt2g0kpnn4.html
DEBUG:ykdl.util.http:get_response> hit cache URL: https://www.iqiyi.com/v_mt2g0kpnn4.html
DEBUG:ykdl.util.http:get_response> URL: https://www.iqiyi.com/v_mt2g0kpnn4.html
DEBUG:ykdl.util.http:get_response> hit cache URL: https://www.iqiyi.com/v_mt2g0kpnn4.html
.......
.......
重复1000次
ERROR:YKDL:RecursionError('maximum recursion depth exceeded while calling a Python object')

如果你有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

爱奇艺视频下载失败, 控制台会输出以上日志1000次, 然后显示递归到达最大次数, 加--no-http-cache参数也无效..求解决..
![20240402232650](https://github.com/SeaHOH/ykdl/assets/24788988/49fee97b-166e-4f5f-a470-69f4db703236)
![20240402232715](https://github.com/SeaHOH/ykdl/assets/24788988/77da00fd-a207-4c7b-a689-f382899bf23c)

**Comment by SeaHOH** [comment]
请更新
